set nocompatible

" Boot Pathogen
runtime bundle/vim-pathogen/autoload/pathogen.vim
execute pathogen#infect()
execute pathogen#helptags()

" Use F2 to toggle paste mode
set pastetoggle=<F2>

" Don't unselect block after indent/outdent
vnoremap < <gv
vnoremap > >gv

" When pasting over a selection, don't copy the replaced text
vnoremap p "_dP

" New splits should open below/right of where we currently are
set splitbelow
set splitright

" Highlight search results
set hlsearch

" Enable line numbering
set number

" Enable the mouse
set mouse=a

" Disable the auto-loading of outside changes; I want to be asked
set noautoread

" Disable folding
set nofoldenable

" Swap file location
set directory=~/tmp/.vim//

" Bells of any kind are annoying
set visualbell t_vb=
set noerrorbells

" Theme/Colors
set colorcolumn=80,132
set cursorline
colorscheme mustang
hi CursorLine cterm=NONE

" GVIM/MacVIM options
if has("gui_running")
    " Hide the toolbar
    set guioptions-=T

    " Set the font
    if has("gui_macvim")
        set guifont=Inconsolata:h14
    else
        set gfn=Inconsolata\ Medium\ 14
    endif
endif

" Language-specific options
let g:polyglot_disabled = []  " Disable languages from vim-polygot
let g:vim_json_syntax_conceal = 0  " Don't hide stuff from me

" Tabs
set tabstop=4
set shiftwidth=4
set softtabstop=4
set expandtab

" Exceptions to my 'tabs are 4 spaces' rule
au FileType html,javascript,json setlocal tabstop=2 shiftwidth=2 softtabstop=2
au FileType go setlocal noexpandtab

" Local overrides
let $LOCALFILE=expand("~/.vimrc_local")
if filereadable($LOCALFILE)
    source $LOCALFILE
endif

