set nocompatible
set encoding=utf-8

"Pathogen
runtime bundle/vim-pathogen/autoload/pathogen.vim
call pathogen#infect()
call pathogen#helptags()

"Colors and highlighting
syntax on
if has("gui_running")
    set t_Co=256
    colorscheme badwolf
else
    if $TERM =~ '^xterm'
        set t_Co=256
        colorscheme badwolf
    elseif $TERM =~ '^screen-bce'
        set t_Co=256
        colorscheme badwolf
    elseif $TERM =~ '^rxvt'
        set t_Co=88
    elseif $TERM =~ '^linux'
        set t_Co=8
    else
        set t_Co=16
    endif
endif
if exists('+colorcolumn')
    let &colorcolumn="80,".join(range(132,320),",")
    highlight ColorColumn ctermbg=235 guibg=#2c2d27
endif
set cursorline
hi CursorLine cterm=NONE

"Mouse stuff
if !has("gui_running")
    if $TERM =~ '^xterm'
        set mouse=a
    elseif $TERM =~ '^screen-bce'
        set mouse=a
    endif
endif

"Line numbering
set nu

"Autoindent
filetype plugin indent on

"Tabs
set tabstop=4
set shiftwidth=4
set softtabstop=4
set expandtab
set smarttab
au FileType yaml setlocal tabstop=2 shiftwidth=2 softtabstop=2

"Searching options
set hlsearch
set incsearch
nnoremap <CR> :nohls<CR><CR>

"Set window title to filename
set title

"Status bar options
set ruler
set showcmd
set laststatus=2

"Fonts
if has("gui_running")
    if has("gui_macvim")
        set guifont=Inconsolata:h12
    else
        set gfn=Inconsolata\ Medium\ 12
    endif
endif

"Misc GUI options
if has("gui_running")
    set guioptions-=T
endif

"Stop it from beeping at us
set visualbell t_vb=
set noerrorbells

"Don't unselect block after indent/outdent
vnoremap < <gv
vnoremap > >gv

"Splitting options
set splitbelow
set splitright

"Easy window navigation
nmap <silent> <A-Up> :wincmd k<CR>
nmap <silent> <A-Down> :wincmd j<CR>
nmap <silent> <A-Left> :wincmd h<CR>
nmap <silent> <A-Right> :wincmd l<CR>

"Key rebinds
nmap <F1> <nop>
set pastetoggle=<F2>
vnoremap p "_dP

"Command aliases
command WQ wq
command Wq wq
command W w
command Q q

"Fix delete/backspace
set backspace=indent,eol,start

"Directory settings
set directory=~/tmp/.vim//

"Plugin configs
let g:vim_json_syntax_conceal = 0
let g:airline_theme='badwolf'
let g:airline_left_sep=''
let g:airline_right_sep=''

"Local overrides
let $LOCALFILE=expand("~/.vimrc_local")
if filereadable($LOCALFILE)
    source $LOCALFILE
endif

